### ISSUE TITLE
Setting GPS origin (Syncing AirSim with Mapbox)

### ISSUE THREAD

**Issue by jasonhbartlett** [Microsoft/AirSim#1634]
Windows 10 Pro
VC++ and 8.1 SDK
Unreal 4.18
PX4 release v1.82 SITL running in BashOnWindows

I can't seem to get the GPS position to change to anything other than the default Microsoft location.  Settings file looks like this:
```yaml
{
  "SettingsVersion": 1.2,
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SimMode": "Multirotor",
  "Vehicles": {
    "PX4": {
      "VehicleType": "PX4Multirotor",
      "UseSerial": false,
      "SitlPort": 14540,
      "UdpPort": 14560
    },
    "OriginGeopoint": {
      "Latitude": 22.915464,
      "Longitude": -59.975619,
      "Altitude": 20
    }
  }
}
```
(Note: GPS location changed for privacy.)
Have changed the settings in the PX4 terminal:
![image](https://user-images.githubusercontent.com/22244576/50034987-bed7ea80-ffcd-11e8-8549-98f73b49ce7d.png)

But when I play the Blocks environment and then open QGroundControl it always brings me to the Microsoft campus!

Are those default GPS coordinates still hardcoded into the program somewhere and my Settings.json OrginGeopoint being ignored?
