### ISSUE TITLE
Unity has outdated data structure when parsing elements of the settings.json file

### ISSUE THREAD

**Issue by jasonhbartlett** [Microsoft/AirSim#1696]
Unity has outdated data structure when parsing elements of the settings.json file.
To reproduce: 
When PX4 in settings file. 
```yaml
{
    "SettingsVersion": 1.2,
    "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
    "SimMode": "Multirotor",
    "Vehicles": {
        "PX4": {
          "VehicleType": "PX4Multirotor"
        }
      }
}
```

![image](https://user-images.githubusercontent.com/22244576/51041153-4db53400-1587-11e9-9813-3b4eb21cf539.png)

I believe the structs located in AirSim/Unity/UnityDemo/Assets/AirSimAssets/Scripts/Utilities/AirSimSettings.cs script need to be updated to be able to read the "Vehicles" data structure.  These structs have been updated and no longer use the DefaultVehcileConfig element which appears to have been removed back on May 17th with the following merge:
53cdcde41a9c325ba34d06b02a45d960bdb543ca

I have noted a temporary work-around in Issue #1617
